### ISSUE TITLE
Crash after the first transcription

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/noa-for-ios#55]
From Discord: https://discord.com/channels/963222352534048818/1137129147764846773
> The crash is on the app side. Consistently happens after the first (successful) run
> Crash flow - run first transcription, get an answer from ChatGPT, shows in the app + Monocle screen.
> Tap again to transcribe, start talking, app starts to transcribe --> Crash

**Comment by siliconwitch** [comment]
Likely fixed in the coming update, but we'll keep an eye out for it
